#!/bin/sh
# Waits until the given host and port are open.

usage() {
  cat <<EOF
  Usage: wait-for-open-port HOST PORT

  Waits for the given PORT to be open on HOST, re-checks every second.

  Use in conjunction with timeout.
EOF
}

check_args() {
  if [ "$#" -ne 2 ]; then
      echo "Illegal number of parameters"
      usage
      return 1
  fi
  return 0
}

main() {
  local host=$1;
  local port=$2;
  while ! nc -z -w5 $host $port; do
    sleep 1
  done
  exit 0;
}

if check_args "$@"; then
    main "$@"
fi
